cc_library(
    name = "projLib",
    #srcs = glob(["**/*.cpp"]),
    srcs = ["Base.cpp","PrivDerived.cpp","ProtDerived.cpp","PublicDerived.cpp"],
    #hdrs = glob(["**/*.h"]),
    hdrs = ["Base.h","PrivDerived.h","ProtDerived.h", "PublicDerived.h"],
    visibility = ["//visibility:public"],
)
